language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
- gem install sass -v 3.2.19
- gem install compass
- git config --global user.email "timvanlaer@gmail.com"
- git config --global user.name "Travis-CI"
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com:timvlaer/ho-gids.git" > .git/credentials
- grunt build:phonegap
- git remote rm origin
- git remote add origin https://timvlaer:${GH_TOKEN}@github.com/timvlaer/ho-gids.git
- git add --all www
- git commit -m"New Phonegap Build by Travis-CI"
- git push origin master
env:
  global:
    secure: VYAsctqe/zElIramGmpJjKMGGr+qPfQFb/NfdQ9otgj8c1022N1ilbmMybNm/JQcQBZEwjjgEcApjsn+WLzBfxg+B7EPih9FYUp1b0n6blfDCEdU9k08NsbALv8KVnKtJQ7buP0Pw0mXByZvrRMBXnHk0m+QO4pvkc5naJa3zAw=
